services:

  postgres:
    image: postgres:18
    command:
      - postgres
      - -c
      - max_connections=320
      - -c
      - shared_buffers=512MB
      - -c
      - effective_cache_size=1536MB
      - -c
      - work_mem=8MB
      - -c
      - maintenance_work_mem=128MB
    container_name: postgres
    environment:
      POSTGRES_DB: psychologicaltestsdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1111
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./scripts/init-db-prod.sql:/docker-entrypoint-initdb.d/init-db-prod.sql

  postgres-db-backup:
    image: prodrigestivill/postgres-backup-local
    container_name: postgres-db-backup
    restart: always
    volumes:
      - ./backups:/backups
    links:
      - postgres
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=psychologicaltestsdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1111
      - SCHEDULE=@monthly
      - BACKUP_KEEP_DAYS=180
      - BACKUP_SUFFIX=.sql.gz

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      SPRING_PROFILES_ACTIVE: default

  users-service:
    build: ./users-service
    container_name: users-service
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE: 20
      SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE: 5
      SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT: 10000
      SPRING_DATASOURCE_HIKARI_IDLE_TIMEOUT: 30000
      SPRING_DATASOURCE_HIKARI_MAX_LIFETIME: 900000
    depends_on:
      - postgres
      - redis
      - eureka-server

  methodologies-service:
    build: ./methodologies-service
    container_name: methodologies-service
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE: 20
      SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE: 5
      SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT: 10000
      SPRING_DATASOURCE_HIKARI_IDLE_TIMEOUT: 30000
      SPRING_DATASOURCE_HIKARI_MAX_LIFETIME: 900000
    depends_on:
      - users-service

  tests-service:
    build: ./tests-service
    container_name: tests-service
    ports:
      - "8083:8083"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE: 220
      SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE: 20
      SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT: 10000
      SPRING_DATASOURCE_HIKARI_IDLE_TIMEOUT: 30000
      SPRING_DATASOURCE_HIKARI_MAX_LIFETIME: 900000
      SERVER_TOMCAT_THREADS_MAX: 800
      SERVER_TOMCAT_ACCEPT_COUNT: 1000
      SERVER_TOMCAT_MAX_CONNECTIONS: 20000
    depends_on:
      - methodologies-service

  attempts-service:
    build: ./attempts-service
    container_name: attempts-service
    ports:
      - "8084:8084"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE: 20
      SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE: 5
      SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT: 10000
      SPRING_DATASOURCE_HIKARI_IDLE_TIMEOUT: 30000
      SPRING_DATASOURCE_HIKARI_MAX_LIFETIME: 900000
    depends_on:
      - tests-service

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - users-service
      - methodologies-service
      - tests-service
      - attempts-service

volumes:
  postgres_data:
