server:
  port: 8081

token:
  signing:
    key: VRohBVW65HZZQr2xVUSfgo4r9bbfIDIwaz6BH0ktJi0

admin:
  limits:
    max-super-admins: 2

spring:
  application:
    name: users-service

  profiles:
    default: dev

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    default-schema: users
    liquibase-schema: users

  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: false

  jackson:
    mapper:
      sort-properties-alphabetically: false

management:
  endpoints:
    web:
      exposure:
        include: health,info