spring:
  application:
    name: psychologicalTestsApplication

  docker:
    compose:
      enabled: false

  datasource:
    url: jdbc:postgresql://localhost/psychologicalTestsDB
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml

  jackson:
    mapper:
      sort-properties-alphabetically: false