spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://${DB_HOST:postgres}:${DB_PORT:5432}/${DB_NAME:psychologicaltestsdb}?currentSchema=tests}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      port: ${REDIS_PORT:6379}
      host: ${REDIS_HOST:redis}

token:
  signing:
    key: ${TOKEN_SIGNING_KEY}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://eureka-server:8761/eureka}
    register-with-eureka: true
    fetch-registry: true
    should-enforce-registration-at-init: false
    healthcheck:
      enabled: true
    registry-fetch-interval-seconds: 30
    eureka-server-connect-timeout-seconds: 5
    eureka-server-read-timeout-seconds: 5
