server:
  port: 8083

token:
  signing:
    key: VRohBVW65HZZQr2xVUSfgo4r9bbfIDIwaz6BH0ktJi0

spring:
  application:
    name: tests-service

  profiles:
    default: dev

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    default-schema: tests
    liquibase-schema: tests

  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  jackson:
    mapper:
      sort-properties-alphabetically: false

management:
  endpoints:
    web:
      exposure:
        include: health,info